force-app/main/default/objects/ad_mapping__c/ad_mapping__c.object-meta.xml
<CustomObject>
    <description>Mapping between profiles, permission sets and AD groups</description>
    <label>AD Group Mapping</label>
    <nameField>
        <displayFormat>ADGM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AD Group Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ad_mapping__c/fields/AD_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>AD_Group_Name__c</fullName>
    <label>AD Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ad_mapping__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/wsd_WebServiceUtil.cls
public with sharing class wsd_WebServiceUtil {
	
	// Messages
	public static final String ERR_MSG_INT_SVR_ERR = 'Internal Server Error';
	public static final String ERR_MSG_INVALID_URI = 'Invalid URL format provided';
	public static final String ERR_MSG_INVALID_BODY= 'Invalid Request Body provided';

	public static void setSuccess(wsd_WebServiceResponse responseBody, RestResponse res, Integer statusCode){
		responseBody.data.put('success',true);
		res.statusCode = statusCode;
	}

	public static void setError(wsd_WebServiceResponse responseBody, RestResponse res, String message, Integer statusCode){
		responseBody.data.put('success',false);
		responseBody.data.put('errorMessage',message);
		res.statusCode = statusCode;
	}

	public static void setException(wsd_WebServiceResponse responseBody, RestResponse res, Exception e, Integer statusCode){
		responseBody.data.put('success',false);
		responseBody.data.put('errorMessage',e.getMessage());
		responseBody.data.put('stackTraceString',e.getStackTraceString());
		res.statusCode = statusCode;
	}

	public static void setRequestInfo(wsd_WebServiceResponse responseBody, RestRequest req){
		Map<String,Object> requestInfo = new Map<String,Object>();
		requestInfo.put('httpMethod',	req.httpMethod);
		requestInfo.put('requestURI',	req.requestURI);
		requestInfo.put('remoteAddress',req.remoteAddress);
		responseBody.data.put('requestInfo', requestInfo);
	}

	// Very bad method, not bulkyfied, DEMO ONLY never implement this way
	public static String getProfileIdBasedOnAdName(String adName){
		ad_mapping__c profileMapping	= [SELECT Name__c, Ad_Group_Name__c FROM ad_mapping__c WHERE Type__c = 'Profile' AND Ad_Group_Name__c = :adName LIMIT 1];
		return [SELECT Id FROM Profile WHERE Name = :profileMapping.Name__c LIMIT 1].Id;
	}

	// Even worse method, not bulkyfied, DEMO ONLY never implement this way
	public static String getPermissionSetIdBasedOnAdName(String adName){
		ad_mapping__c permissionSetMapping= [SELECT Name__c, Ad_Group_Name__c FROM ad_mapping__c WHERE Type__c = 'Permission Set' AND Ad_Group_Name__c = :adName LIMIT 1];
		return [SELECT Id FROM PermissionSet WHERE Label = :permissionSetMapping.Name__c LIMIT 1].Id;
	}
}